---
#- hosts: localhost
#  tasks:
- name: Create an ec2 instance spot instance 
  block:
    - name: Launch ec2 spot           
      ec2:
        region: us-east-1
        spot_price: '0.01'
        spot_wait_timeout: 600
        key_name: '{{ ec2_key[env] }}'
        group: default
        instance_type: t2.micro
        image: "{{ ec2_image['ubuntu'] }}"
        wait: yes
        wait_timeout: 500
        count: 1
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 8
            delete_on_termination: yes
        instance_tags:
          Name: created_from_ansible
          service: '{{service}}'
          environment: '{{env}}'
          provision_state: new
        vpc_subnet_id: subnet-8c9ecfd1
        assign_public_ip: yes
        instance_initiated_shutdown_behavior: terminate
      register: ec2
    - name: Wait for SSH to come up
      delegate_to: '{{ item.public_ip }}'
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: '{{ ec2.instances }}'
    - name : Add instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        group: launched
      loop: "{{ ec2.instances }}"
    - name: List Instance Ids
      debug: 
        msg: '{{ item.id }} {{ item.public_ip }}'
      with_items: '{{ ec2.instances }}'    
  connection: local